In [15]:
import numpy as np

In [16]:
np

<module 'numpy' from '/workspaces/machine-learning-zoomcamp-homework/.venv/lib/python3.12/site-packages/numpy/__init__.py'>

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.full(10, 3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

In [20]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
a[5] = 11

In [23]:
a

array([ 1,  2,  3,  4,  5, 11,  7,  8,  9, 10])

In [25]:
np.arange(1, 20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [26]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [28]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [34]:
n[1, 1] = 20

In [35]:
n

array([[ 1,  2,  3],
       [ 4, 20,  6],
       [ 7,  8,  9]])

In [37]:
n[2] = [10, 11, 12]

In [39]:
n

array([[ 1,  2,  3],
       [ 4, 20,  6],
       [10, 11, 12]])

In [42]:
n[:, 2] = [7, 14, 21]

In [44]:
n

array([[ 1,  2,  7],
       [ 4, 20, 14],
       [10, 11, 21]])

In [82]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [85]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [87]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [89]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
a + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [92]:
a * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [93]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [95]:
(10 + (a * 2)) **2

array([100, 144, 196, 256, 324, 400, 484, 576, 676, 784])

In [100]:
b = (10 + (a * 2)) **2 / 2

In [102]:
b

array([ 50.,  72.,  98., 128., 162., 200., 242., 288., 338., 392.])

In [104]:
a + b

array([ 50.,  73., 100., 131., 166., 205., 248., 295., 346., 401.])

In [106]:
a * b

array([   0.,   72.,  196.,  384.,  648., 1000., 1452., 2016., 2704.,
       3528.])

In [108]:
a / b

array([0.        , 0.01388889, 0.02040816, 0.0234375 , 0.02469136,
       0.025     , 0.02479339, 0.02430556, 0.02366864, 0.02295918])

In [110]:
a >= 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [112]:
b > a

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [114]:
a > b

array([False, False, False, False, False, False, False, False, False,
       False])

In [117]:
a[b > a]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
a.min()

np.int64(0)

In [121]:
a.max()

np.int64(9)

In [123]:
a.sum()

np.int64(45)

In [130]:
b.mean()

np.float64(197.0)

In [133]:
a.std()

np.float64(2.8722813232690143)

In [135]:
n.sum()

np.int64(90)

In [136]:
n.max() 

np.int64(21)