In [91]:
import numpy as np

In [92]:
np

<module 'numpy' from '/workspaces/machine-learning-zoomcamp-homework/.venv/lib/python3.12/site-packages/numpy/__init__.py'>

In [93]:
# VECTOR OPERATIONS
a = np.array([2, 4, 6, 8])

In [94]:
a

array([2, 4, 6, 8])

In [95]:
b = np.array([1, 3, 5, 7])

In [96]:
b

array([1, 3, 5, 7])

In [97]:
2 * a

array([ 4,  8, 12, 16])

In [98]:
3 * b

array([ 3,  9, 15, 21])

In [99]:
a + b

array([ 3,  7, 11, 15])

In [100]:
a - b

array([1, 1, 1, 1])

In [101]:
a * b


array([ 2, 12, 30, 56])

In [102]:
# MULTIPLICATION AND DOT PRODUCT
# Vector - Vector Multiplication (Dot Product)

In [103]:
u = np.array([2, 4, 5, 6])

In [104]:
u

array([2, 4, 5, 6])

In [105]:
v = np.array([1, 0, 0, 2])

In [106]:
v

array([1, 0, 0, 2])

In [107]:
u.shape[0]

4

In [108]:
v.shape[0]

4

In [109]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0], "Vectors must be the same length"
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [110]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [111]:
u.dot(v)

np.int64(14)

In [112]:
# Matrix - Vector Multiplication

In [113]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [114]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [115]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [116]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [117]:
U.shape[0]

3

In [118]:
V.shape[0]

4

In [119]:
def MATRIX_VECTOR_MULTIPLICATION(U, v):
    assert U.shape[1] == v.shape[0], "Incompatible shapes"
    m = U.shape[0]
    n = U.shape[1]
    result = np.zeros(m)
    for i in range(m):
        for j in range(n):
            result[i] = result[i] + U[i, j] * v[j]
    return result

In [120]:
MATRIX_VECTOR_MULTIPLICATION(U, v)  

array([14.,  5.,  5.])

In [121]:
U.dot(v)    

array([14,  5,  5])

In [122]:
# Matrix - Matrix Multiplication

In [123]:
def MATRIX_MATRIX_MULTIPLICATION(U, V):
    assert U.shape[1] == V.shape[0], "Incompatible shapes"
    m = U.shape[0]
    n = U.shape[1]
    p = V.shape[1]
    result = np.zeros((m, p))
    for i in range(m):
        for j in range(p):
            for k in range(n):
                result[i, j] = result[i, j] + U[i, k] * V[k, j]
    return result

In [124]:
MATRIX_MATRIX_MULTIPLICATION(U, V)  

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [125]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [126]:
# IDENTITY MATRIX

In [127]:
I = np.eye(4)

In [128]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [129]:
U.dot(I)

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

In [130]:
# INVERSE MATRIX

In [131]:
# Define a 3x3 matrix V
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [132]:
# Make a new matrix Vs (Square Matrix) with the first three rows of V
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [133]:
Vs_inv = np.linalg.inv(Vs)    
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [134]:
Vs_inv.dot(Vs)  

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])