In [53]:
import numpy as np  
import pandas as pd 


In [54]:
# Question 1

pd.__version__

'2.3.2'

In [55]:
# Loading the data
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [56]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [57]:
# Create a sample DataFrame
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [58]:
# Question 2

len(df)
print("Number of records:", len(df))

Number of records: 9704


In [59]:
# Question 3

# Check the unique values in the 'fuel_type' column
unique_fuel_types = df['fuel_type'].unique()
print("Unique fuel types:", unique_fuel_types)

# Count how many unique ones there are
num_fuel_types = df['fuel_type'].nunique()
print("Number of unique fuel types:", num_fuel_types)


Unique fuel types: ['Gasoline' 'Diesel']
Number of unique fuel types: 2


In [60]:
# Question 4

# Count missing values in each column
missing_counts = df.isna().sum()
print("Missing values per column:\n", missing_counts)

# Count columns with any missing values
num_missing_columns = (missing_counts > 0).sum()
print("\nNumber of columns with missing values:", num_missing_columns)

# (Optional) List the columns with missing values
missing_columns = missing_counts[missing_counts > 0].index.tolist()
print("Columns with missing values:", missing_columns)

Missing values per column:
 engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

Number of columns with missing values: 4
Columns with missing values: ['num_cylinders', 'horsepower', 'acceleration', 'num_doors']


In [61]:
# Question 5

# Check unique origins to confirm 'Asia' is present
print("Unique origins:", df['origin'].unique())

# Filter for Asia and find max fuel efficiency
asia_cars = df[df['origin'] == 'Asia']  # Select rows where origin is 'Asia'
max_efficiency = asia_cars['fuel_efficiency_mpg'].max()  # Get the maximum MPG
print("Maximum fuel efficiency for Asia cars:", max_efficiency)

Unique origins: ['Europe' 'USA' 'Asia']
Maximum fuel efficiency for Asia cars: 23.759122836520497


In [62]:
# Question 6

# Step 1: Median horsepower before filling
median_hp_before = df['horsepower'].median()
print("Median horsepower before filling:", median_hp_before)

# Step 2: Most frequent (mode) horsepower value
mode_hp = df['horsepower'].mode()[0]  # mode() returns a Series; [0] gets the first (most frequent)
print("Most frequent horsepower value:", mode_hp)

# Step 3: Fill missing values with the mode
df['horsepower_filled'] = df['horsepower'].fillna(mode_hp)  # Creates a new column with filled values

# Step 4: Median horsepower after filling
median_hp_after = df['horsepower_filled'].median()
print("Median horsepower after filling:", median_hp_after)

# Check if it changed
if median_hp_after > median_hp_before:
    print("Yes, it increased")
elif median_hp_after < median_hp_before:
    print("Yes, it decreased")
else:
    print("No")

Median horsepower before filling: 149.0
Most frequent horsepower value: 152.0
Median horsepower after filling: 152.0
Yes, it increased


In [79]:
# Question 7

# 1. Select all cars from Asia

asia_cars = df[df['origin'] == 'Asia']
asia_cars

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  horsepower_filled  
8               16.823554              174.0  
12              16.175820              145.0  
14              11.871091              160.0  
20              18.889083              197.0  
21              16.077730              133.0  
...                   ...                ...  
9688            11.054830              152.0  
9692            11.711653              188.0  
9693            17.202782              148.0  
9698            13.933716              131.0  
9703            14.884467              140.0  

[3247 rows x 12 columns]

In [83]:
# 2. Select only 'vehicle_weight' and 'model_year' columns

asia_cars_selected = asia_cars[['vehicle_weight', 'model_year']]
asia_cars_selected.head()

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016

In [100]:
# 3. Select the first 7 values

asia_cars_7 = asia_cars_selected.head(7)
asia_cars_7 

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [ ]:
# 4. Extract and display the underlying NumPy array from the DataFrame

X = asia_cars_7 .to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [ ]:
# 5. Compute the matrix multiplication of the transpose of X and X. Call the result XTX

XTX = X.T @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [ ]:
# 6. Invert XTX

XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [ ]:
# 7. Create an array y with the following values: 1100, 1300, 800, 900, 1000, 1100, 1200.

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y


array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [ ]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

w = XTX_inv @ X.T @ y
w

array([0.01386421, 0.5049067 ])

In [ ]:
# 9. What's the sum of all the elements of the result?

result_sum = np.sum(w)
result_sum
print("The sum of the elements of w is:", result_sum)

The sum of the elements of w is: 0.5187709081074016
